DROP DATABASE if EXISTS PokedexDB;
CREATE DATABASE IF NOT EXISTS PokedexDB;

USE PokedexDB;

CREATE TABLE Pokemon_Set(
	setId INT PRIMARY KEY AUTO_INCREMENT,
	setName VARCHAR(50)
);

CREATE TABLE Pokemon(
	cardId INT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(100) NOT NULL,
	cardNumber VARCHAR(10) NOT NULL,
	isRare TINYINT(1) NULL,
	quantity INT NULL DEFAULT 1,
	setId INT,
	FOREIGN KEY (setId) REFERENCES Pokemon_Set(setId)
);


